[package]
name = "kern-core"
version = "0.1.2"
edition = "2024"

[dependencies]
# Metin ve Hata Motoru (The Brain)
ropey = "1.6.1"       
thiserror = "2.0"     

# Arama ve Navigasyon (The Senses)
ignore = "0.4.25"     
fuzzy-matcher = "0.3.7"  # Akıllı Arama (Güncel) ✅
rayon = "1.11.0"      

# Sistem ve İzleme (The Reflexes)
notify = "8.2.0"
serde = { version = "1.0", features = ["derive"] }